feat: input-styles
Mentor-Cycle/mentor-cycle-fe pull request #16
Opened 2023-03-04 20:29 UTC by salviotonon

### Create Input Style with native validation I don't use libs

I have added some improvements to the validation logic, including displaying error messages and highlighting invalid input. I have also included some accessibility features with Radix UI

### Criado o Input Style com validação nativa, validações feitas sem auxilio de libs

Nesta versão atualizada, fiz melhorias na lógica de validação, incluindo a exibição de mensagens de erro e destaque para entradas inválidas. Também adicionei recursos de acessibilidade com a Label do Radix UI

2023-03-06 02:19 UTC, oliveirabalsa commented on src/components/Input/Input.tsx
> +  ...props
Embora voĉe esteja pegando todas as props restantes vc não tá passando ao componente

2023-03-06 02:20 UTC, oliveirabalsa commented on src/components/Input/Input.tsx
> +      <input
```sug{gestion
      {...props}
```

2023-03-06 02:21 UTC, oliveirabalsa commented on src/components/Input/Input.tsx
> +      {label}
```suggestion
      <input
      {...props}
```

2023-03-06 02:24 UTC, oliveirabalsa approved these changes

2023-03-07 14:13 UTC, thiagopuntar requested changes

2023-03-08 12:41 UTC, salviotonon commented on src/components/Input/Input.tsx
> +  pattern,
removi as props que nao precisavam, algumas eu mantive como a label, a size e a disabled.

2023-03-13 23:32 UTC, merged