feat: create stepper
Mentor-Cycle/mentor-cycle-fe pull request #17
Opened 2023-03-05 20:28 UTC by salviotonon

# This pull request adds a new Stepper component.

### Description
The Stepper component receives two props: steps, which is an array of step numbers, and currentStep, which is the current step number. The component then renders a sequence of steps with a separator between them.

### Descrição
Essa pull request adiciona um novo componente Stepper.
O componente Stepper recebe duas props: steps, que é um array de números de etapa, e currentStep, que é o número da etapa atual. O componente então renderiza uma sequência de etapas com um separador entre elas.

2023-03-06 02:15 UTC, oliveirabalsa approved these changes

2023-03-07 14:33 UTC, thiagopuntar requested changes
E aí bro, tudo certo? Curti bastante, só o comentário de não criar uma nova classe do tailwind.

2023-03-07 14:33 UTC, thiagopuntar commented on src/components/Stepper/Stepper.tsx
> +  const completedStepClasses = "step-item-completed bg-primary-03";
Eu deixaria os estilos aqui ao invés de criar uma classe específica

2023-03-13 17:09 UTC, oliveirabalsa approved these changes

2023-03-13 17:16 UTC, merged