feat(tailwind.config): Adds color theme and font family
Mentor-Cycle/mentor-cycle-fe pull request #2
Opened 2023-02-10 21:51 UTC by salviotonon

**Implementation of Style Guide Colors and Typography**

This pull request includes the implementation of the color palette and typography described in the Figma app style guide. I use Tailwind to work with these constants and bring them into our code. @thiagopuntar @oliveirabalsa

2023-02-10 22:12 UTC, thiagopuntar reviewed
Que beleza, primeira PR aberta pro projeto e ficou um trabalho da hora. Parabéns bro, só dois pequenos ajustes e a gente já faz o merge.

2023-02-10 22:12 UTC, thiagopuntar commented on tailwind.config.js
> +        poppins: ["Poppins", "sans-serif"],
Aqui eu acho que seria melhor usar o sans, igual mostra lá na doc.

2023-02-10 22:12 UTC, thiagopuntar commented on src/styles/Home.module.css
> -.container {
Pode excluir esse arquivo! Acho que não vamos utilizar ele mais. Excelente trabalho.

2023-02-10 22:48 UTC, oliveirabalsa commented
> 

Que top! Só essas pendências do Puntar e resolver esses merge conflicts

2023-02-12 14:38 UTC, thiagopuntar requested changes
Salve bro, tudo certinho? Eu tinha comentado para abrir uma outra PR para o button em cima dessa branch que você trabalhou. A parte de estilo tá certinha e aí a gente já consegue aprovar e mergear.

Sobre o button eu tenho alguns comentários mas eu faço na outra PR pra gente não estender o trabalho dessa.

Forte abraço e agradeço muito sua contribuição.

2023-02-12 15:44 UTC, thiagopuntar approved these changes

2023-02-13 13:31 UTC, thiagopuntar commented
@salviotonon salve bro! 
Pra não te pedir mais um rebase fiz uma outra branch com suas alterações. https://github.com/Mentor-Cycle/mentor-cycle-fe/pull/5.

Estou fechando!

2023-02-13 13:31 UTC, closed without merging