Feat login page
Mentor-Cycle/mentor-cycle-fe pull request #22
Opened 2023-03-16 01:18 UTC by salviotonon

## Create Mentor Cycle Login Page

Created the Mentor Cycle login page. The code utilizes GraphQL with Apollo Client to authenticate a user through a login mutation.Due to integration reasons with the backend, the "remember password" logic was not implemented.

Criado a  página de login do Mentor Cycle. O código utiliza GraphQL com Apollo Client para autenticar um usuário por meio de uma mutation de login. Por motivos de integração com o backend não foi realizado a logica de "lembrar senha"
</br>
<div style={{display: "flex"; justify-content: "center"; align-items: "center"}}>
<img src="https://user-images.githubusercontent.com/110191259/225484288-7b1afe04-d134-4015-b226-c0f1e8464279.jpg" alt="mentor1" />
</br>
<img src="https://user-images.githubusercontent.com/110191259/225484299-841f290d-7138-4718-8c22-3c4b228a8af5.jpg" alt="mentor2" />
</br>
<img src="https://user-images.githubusercontent.com/110191259/225484304-82ecb293-de0d-4d83-af30-c994859dbba9.jpg" alt="mentor3" />
</div>

2023-03-17 01:33 UTC, oliveirabalsa approved these changes

2023-03-17 01:33 UTC, oliveirabalsa commented on src/lib/apollo-client.ts
> +export default client;
Acho que poderia mover esse arquivo para outra pasta, geralmente o padrão seria na `src` você criar uma pasta `services/apollo/client.ts`.

2023-03-17 01:33 UTC, oliveirabalsa commented on src/pages/signin.tsx
> +import CheckboxRadix from "@components/Checkbox/Checkbox";
Como o Checkbox tem a pasta index, daria para usar apenas `"@components/Checkbox"`

2023-03-17 01:34 UTC, oliveirabalsa requested changes

2023-03-17 01:34 UTC, oliveirabalsa commented on src/lib/apollo-client.ts
> +export default client;
Caso tenha duvidas pode chamar

2023-03-17 12:48 UTC, thiagopuntar requested changes
Impressionante como sempre Salvio, muito obrigado pelas incontáveis ajudas e contribuições.
Fiz alguns comentários, qualquer coisa só chamar!

2023-03-17 12:48 UTC, thiagopuntar commented on src/components/Checkbox/Checkbox.tsx
> +const CheckboxRadix = ({ label, id, className, ...props }: CheckBoxType) => {
Acho que o Checkbox tem que ser Checkbox e o que você importou do Radix ser CheckboxRadix.
Porque o checkbox que usamos na aplicação é bom ser "invisível" a implementação para quem vai utilizar saca? Se amanhã quisermos usar alguma outra lib só trocamos no checkbox e quem consome não precisa mudar nada.

2023-03-17 12:48 UTC, thiagopuntar commented on src/pages/signin.tsx
> +  const handleInputChange = (name: string, value: string) => {
Você pode passar o event e pegar o name do event.target. Dessa forma não precisa passar 2 parâmetros.
Ou não precisa usar controlled components. Pode simplesmente deixar o user setar as coisas e na hora do submit você consegue pegar as informações do form via ref. bom que não re renderiza nada. É como o react hook forms trabalha, se não me engano.

2023-03-17 12:48 UTC, thiagopuntar commented on src/pages/signin.tsx
> +        variables: { email: formState.username, password: formState.password },
Se for fazer a abordagem de usar uncontrolled components é só fazer um Object.entries(formRef.current) que deve funcionar.

2023-03-17 12:48 UTC, thiagopuntar commented on src/pages/signin.tsx
> +      <div className="relative bg-gradient-to-r from-primary-04 to-primary-02 dark:bg-gradient-to-r dark:from-link-02 dark:to-neutral-02 py-16 col-span-1 md:col-span-6 md:py-0 md:pl-12 lg:pl-32 md:pr
Eu acho que vamos ter que centralizar o conteúdo em telas muito grandes. Depois dá uma testada.
image.png

2023-03-17 12:48 UTC, thiagopuntar commented on src/pages/signin.tsx
> +              <CheckboxRadix
Além de renomear pra Checkbox, acho que vai precisar adicionar o name para poder submeter o formulário como um todo. Pode mandar o campo rememberMe, depois o backend vê como vai tratar. Mas aqui no front a gente já se livra do trampo.

2023-03-17 12:48 UTC, thiagopuntar commented on src/pages/signin.tsx
> +            <Button
Acho que eu colocaria esses buttons fora do elemento form. Um button dentro do form por padrão fica como submit. Acho que podemos ou tirar os buttons de dentro do form ou colocar um type=button neles.

2023-03-17 12:48 UTC, thiagopuntar commented on src/pages/signin.tsx
> +            <Button
Acho que eu colocaria esses buttons fora do elemento form. Um button dentro do form por padrão fica como submit. Acho que podemos ou tirar os buttons de dentro do form ou colocar um type=button neles.

2023-03-17 12:48 UTC, thiagopuntar reviewed
Impressionante como sempre Salvio, muito obrigado pelas incontáveis ajudas e contribuições.
Fiz alguns comentários, qualquer coisa só chamar!

2023-03-19 12:12 UTC, thiagopuntar approved these changes
Excelente como sempre!

2023-03-19 12:15 UTC, merged