[Front-end] - Redimensionar pop-up de agendamento
Mentor-Cycle/mentor-cycle-fe pull request #235
Opened 2023-06-13 16:07 UTC by FelipePEduardo

Nesta tarefa eu arrumei o redimensionamento do pop-up no step 2 para ele ficar do mesmo tamanho do step da etapa anterior e alterei a cor do `<span>Horário: </span>` pois no dark-mode ele estava com a mesma cor do background

Antes:
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/103855358/504bd265-ed7a-4e9b-9859-4a0e2632cf50)

Depois: 
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/103855358/c8ee70f9-d164-419e-a916-7aab20e63421)

2023-06-14 03:02 UTC, oliveirabalsa approved these changes
Show!!!

2023-06-14 22:13 UTC, salviotonon requested changes

2023-06-14 22:13 UTC, salviotonon commented on src/components/Modal/Modal.tsx
>              <div>
valeu pela contribuição !!! Tem um detalhe sobre sua PR. essa task foi criada pela equipe de UI, eles estão pedindo ajuste no componente de steps, aquele que tem a numeração em cima, para continuar com a PR entre em contato com o time de UI no discord e verifique essa situação. A princípio eles pediram ajuste no espaçamento entre a numeração dos steps. Da uma olhada no componente Stepper. valeeu

2023-06-20 02:41 UTC, oliveirabalsa commented on src/components/Modal/Modal.tsx
>              <div>
@FelipePEduardo tem algum feedback sobre as mudanças?

2023-06-24 14:36 UTC, oliveirabalsa commented on src/components/Modal/Modal.tsx
>              <div>
Show cara Boa sorte nessa nova etapa

2023-06-24 14:36 UTC, closed without merging