fix: remove duplicated events
Mentor-Cycle/mentor-cycle-fe pull request #246
Opened 2023-06-17 03:26 UTC by sillasbernardo

Este PR é referente a task #221 no qual removi a duplicidade de mentorias agendadas. Para isto, criei uma validação no input de dados em ScheduleMentorshipModal, linha 97, em que caso a mentoria já tenha sido agendada antes, emite um update alterando o status para "CONFIRM", caso contrário, criar uma nova.

![Mentoria agendada](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/79178423/497c862b-cba1-4b8b-bbe1-b27bfbdf263e)

![Mentoria cancelada](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/79178423/0b95fc30-3be1-447c-87f0-9c15897caf62)

2023-06-18 17:37 UTC, oliveirabalsa approved these changes

2023-06-20 20:20 UTC, oliveirabalsa requested changes
Resolver conflitos

2023-06-23 03:08 UTC, oliveirabalsa approved these changes

2023-06-24 14:39 UTC, oliveirabalsa requested changes

2023-06-24 14:39 UTC, oliveirabalsa commented on src/pages/profile.tsx
> +      </>
@sillasbernardo eu um problema no build:  React Hook useEffect has an unnecessary dependency: 'router.query'. na linha 56;  Só remover a dependencia do useEffect

2023-06-27 16:12 UTC, sillasbernardo commented on src/pages/profile.tsx
> +      </>
Eu criei a variável "router" que estava faltando no componente, por isso useEffect estava com este erro. Após criá-la, atualizei as dependencias. Está resolvido.

2023-07-02 03:55 UTC, oliveirabalsa requested changes

2023-07-02 03:55 UTC, oliveirabalsa commented on src/utils/dashboard-helpers.tsx
> -};
![image](https://github.com/Mentor-Cycle/mentor-cycle-fe/assets/57500163/42b8e2cc-f060-4030-b29d-0703af2e75e1)
@sillasbernardo acho que essa chave era pra ficar, ou alguma outra chave ta errada. Antes de subir tenta rodar yarn build pra validar

2023-07-02 05:34 UTC, sillasbernardo commented on src/utils/dashboard-helpers.tsx
> -};
Erros corrigidos.

2023-07-02 21:18 UTC, oliveirabalsa approved these changes

2023-07-03 11:53 UTC, merged