refactor: context
Mentor-Cycle/mentor-cycle-fe pull request #255
Opened 2023-06-26 00:41 UTC by iannak

2023-06-26 12:45 UTC, salviotonon requested changes

2023-06-26 12:45 UTC, salviotonon commented on src/components/Header/Header.tsx
> +                  email={email}
Conseguimos retirar essa parte do codigo do header, e deixar apenas um hook que abre e fecha o modal atraves do contexto? O codigo do header da aplicação tem muitas responsabilidades, se a gente conseguir abstrair algumas partes dele, vai ficar melhor para manutenção. nesse cenário poderiamos ter algo nessa linha aqui, será que é possivel?
```js
  const ModalSettings = useModalSettings();
  
  //A parte do código que controla o acionamento dos itens do menu
  
  const menuClickActions = {
    editprofile: () => router.push("/profile"),
    darkmode: () => setDarkMode(),
    settings: () => {
     ModalSettings.onOpen() // so precisariamos acionar o hook aqui e conseguiriamos abrir o modal
    },
    logout: logOutUser(),
  };
```

```
ModalSettings.onClose() // algo nessa linha se precisar fechar o modal
```

2023-06-26 15:25 UTC, iannak commented on src/components/Header/Header.tsx
> +                  email={email}
acredito que sim

2023-06-27 11:09 UTC, oliveirabalsa reviewed
Fala Anna desculpa a demora. Seria interessante ter um contexto só modal topo ModalContext, lá vc armazenaria todos os estados de modais, por exemplo "editProfileModal", "settingsModal" e daí usaria um hook por exemplo "useModal" pra poder fazer o open e close deles, acho que seria uma abordagem mais interessante

2023-06-27 11:58 UTC, iannak commented
@oliveirabalsa fechou meu querido, ja fazendo essas alterações

2023-06-27 12:21 UTC, iannak commented
1. Importei o ModalProvider e o useModal do contexto ModalContext.
2. Substituí o estado isModalOpen por openModal e closeModal do contexto ModalContext.
3. Chamei a função openModal para abrir o modal de configurações.
4. Removi o componente <ModalSettings setIsModalOpen={setIsModalOpen} firstName={firstName} email={email} id={id} lastName={lastName} /> do modal de configurações e o coloquei diretamente no local onde o modal é renderizado.
5. Adicionei o ModalProvider ao redor de todo o componente Header.
6. Ajustei as importações para remover a importação duplicada do Modal e remover a importação não utilizada do ModalSettings.

2023-06-27 17:25 UTC, oliveirabalsa commented on src/components/Header/Header.tsx
> +              lastName={lastName}
@iannak essas props poderiam estar dentro do modal uma vez que está utilizando contexto agora, se quiser podemos fazer isso juntos depois. A abordagem que seria top na minha opinião seria tipo

const { openModal } = useModal()

showModal === "settings" && openModal("settings") algo do genero  que poderia se tornar openModal(showModal)

2023-06-27 17:25 UTC, oliveirabalsa commented on src/components/Header/Header.tsx
> +              lastName={lastName}
isso funciona hoje bem parecido com o Toast

2023-06-27 18:16 UTC, iannak commented on src/components/Header/Header.tsx
> +              lastName={lastName}
ahhhh pode ser, se quiser chama quando tiver por ai depois das 18, pode ser?? @oliveirabalsa

2023-07-02 03:53 UTC, oliveirabalsa commented on src/components/Header/Header.tsx
> +              lastName={lastName}
@iannak desculpa a ausência, vamos conectar, sim, essa semana pra ver isso

2023-07-02 22:57 UTC, merged