Feat signup page
Mentor-Cycle/mentor-cycle-fe pull request #29
Opened 2023-03-25 00:53 UTC by salviotonon

## Create SignUp Page

This PR includes the development of the user registration page on the platform. It consists of the following features:

1. Choice of user model.
2. Choice of registration data in three steps: profile, personal information, and contact information.
3. Validation of required fields before moving on to the next step or completing the registration.
4. Call to the back end in the resolver to create a new account using graphql.
5. Responsive of the pages for extra large, desktop, laptop, tablet, xl phone and small phone screen sizes.

## Criado a pagina de cadastro de usuário

Esta PR inclui o desenvolvimento da página de registro de usuários na plataforma. É composta pelas seguintes funcionalidades:

1. Escolha do modelo de usuário (mentor ou mentorado).
2. Escolha dos dados de registro em três etapas: perfil, informações pessoais e informações de contato.
3. Validação dos campos obrigatórios antes de avançar para a próxima etapa ou finalizar o registro.
4. Chamada para o back end no resolver para criar uma conta nova utilizando graphql.
5. Responsividade das paginas para tamanhos de telas extra grandes, desktop, laptop, tablet, celular xl e celular small

![plan](https://user-images.githubusercontent.com/110191259/227668157-fe4351a2-fb98-4ff6-a3d8-6942fc8fe45a.jpg)
![register2](https://user-images.githubusercontent.com/110191259/227668512-4cf0de2d-a955-463b-862f-7b1a479a163e.jpg)
![register3](https://user-images.githubusercontent.com/110191259/227668515-c6216b00-ed9e-472f-a8a7-19a05c4a5c6a.jpg)
![register4](https://user-images.githubusercontent.com/110191259/227668674-132687fd-457f-422c-848c-6c420a17f436.jpg)
![register5](https://user-images.githubusercontent.com/110191259/227668675-0b67d1b8-e405-43cd-81bc-f39acfd4fff8.jpg)

2023-03-30 21:17 UTC, oliveirabalsa requested changes

2023-03-30 21:17 UTC, oliveirabalsa commented on src/components/FormSteps/Profile.tsx
> +    }
```suggestion
    setPasswordError(password !== target.value ? "As senhas não correspondem." : "");
```

2023-03-30 21:17 UTC, oliveirabalsa commented on src/components/LocationSelector/SelectState.tsx
> +    : null;
```suggestion
  const url = selectedCountry && "https://servicodados.ibge.gov.br/api/v1/localidades/estados";
```

2023-03-30 21:17 UTC, oliveirabalsa commented on src/components/LocationSelector/SelectState.tsx
> +      : null;
```suggestion
  const listStates =
    selectedCountry === "Brasil"
      && states?.map(({ nome, sigla }) => (
          <SelectItem key={nome} value={sigla}>
            {nome}
          </SelectItem>
        ));
```

2023-03-30 21:17 UTC, oliveirabalsa commented on src/pages/signup/plan.tsx
> +          <Link href={"/signin"} passHref legacyBehavior>
não entendi o motivo do legacyBehavior o Link de next/link funciona normalmente dessa forma  com `href="/signin"`

2023-03-30 21:17 UTC, oliveirabalsa commented on src/services/fetch/useData.ts
> +};
aqui ficou um pouco confuso, tem ifs dentro de ifs e fica dificil para uma outra pessoa que for utilizar entender o que acontece, existe uma coisa chamda "early return" para evitar if nested. Mas creio que você deva refatorar para cobrir as partes de `getCountries` que comentei você pode criar como funções mesmo` const getCountries = async () => ...` e depois exportar cada uma das funções` return { getCountries, ...}`

2023-03-30 21:17 UTC, oliveirabalsa commented on src/services/fetch/useData.ts
> +};
qualquer duvida pode chamar também

2023-04-01 21:09 UTC, salviotonon commented on src/components/FormSteps/FormSteps.tsx
> +    skills: [],
o formulario só esta recebendo a ultima skill selecionada no select

2023-04-01 21:13 UTC, salviotonon commented on src/components/MultiSelect/MultiSelect.tsx
> +        className="font-normal"
como pegar todas as skills selecionadas do componente pela propriedade "name"?

2023-04-02 19:14 UTC, oliveirabalsa commented
Fala @salviotonon vou criar aqui um plano de ação com umas mudanças
 1 - Remover o processo atual de coleta de dados para um processo de context-api via "FormProvider" algo do tipo, sendo possível o usuário navegar entres os steps sem perder seus dados.
 2 - a cor dos inputs estão iguais aos do placeholder, alterar isso para uma melhor experiência.
 3 - fixar o campo "Brasil" como pais por enquanto, pois não temos cobertura para os demais países.
 4 - existem alguns problemas de escritas como "sobremone" e "seleciona sua especialização".
 5 - o Input de aniversário deverá ser colocado como "dd/mm/yyyy"
 6 - Ao invés de mostrar um alert com "campos obrigatorios" poderia adicionar uma animação na tela balançando o form pra direito e esqueda, ou algo mais simples, deixar os inputs vermelhos, utilizar disso para criar o "react-toastify"(https://trello.com/c/3yf1axiX/113-adicionar-toast-de-mensagem) e mostrar um toast para o usuário.
 7 - Seria interessante deixar o form navegável via os steppers, não é obrigatório mas seria interessante. Com a context-api isso seria melhor

2023-04-06 00:52 UTC, oliveirabalsa approved these changes

2023-04-06 00:52 UTC, merged