feat: create modal component
Mentor-Cycle/mentor-cycle-fe pull request #46
Opened 2023-04-11 20:02 UTC by Aristeu-Miranda

Foi criado o componente "modal" utilizando Radix UI.
Como o modal deverá ser utilizado em algumas partes do template, criei para ele receber "modalOpen" onde quando for utilizado o desenvolvedor podera estilizar a abertura do modal como preferir. Irá receber também um "modalTitle" obrigatório e "modalDescription" e "modalClose" como opcionais. 
Para fechar o modal, terá por padrão o icone de "X" no canto superior direito.
Segue exemplo do modal:
![image](https://user-images.githubusercontent.com/89033182/231275353-db9324d4-c366-421e-8068-4debf31dd917.png)
![image](https://user-images.githubusercontent.com/89033182/231275448-45713521-dfff-44e5-a96c-7fbe1e5c2330.png)

Storybook: O storybook foi construído apenas para mostrar o funcionamento do modal, sem estilizações pré-definidas.

2023-04-12 19:27 UTC, salviotonon requested changes

2023-04-12 22:02 UTC, oliveirabalsa requested changes

2023-04-12 22:02 UTC, oliveirabalsa commented on src/components/Modal/Modal.tsx
> +  modalClose,
então aqui na verdade o modal precisa receber um children,  e o conteúdo de dentro será agnostico e passado via children

2023-04-13 19:50 UTC, oliveirabalsa approved these changes

2023-04-13 19:51 UTC, merged