feat(button): create button/styles
Mentor-Cycle/mentor-cycle-fe pull request #9
Opened 2023-02-15 01:22 UTC by salviotonon

Create Button component with different variants as described in Figma style guide page.

obs: component button stories have been created but need review

2023-02-16 16:10 UTC, oliveirabalsa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Button](https://trello.com/c/wtu4JuWF/56-button)

2023-02-17 14:53 UTC, oliveirabalsa commented
Caraca! Muito bom, parabéns!!!

2023-02-20 12:10 UTC, thiagopuntar requested changes
Olá Salvio, muito obrigado mais uma vez pela sua contribuição. Queria pedir desculpas por ter demorado tanto para revisar, as coisas estão um pouco corridas essas semanas.
Você fez um trabalho fenomenal, bem acima da curva. Parabéns de verdade.

Qualquer dúvida quanto aos pontos levantados e sobre o que é preciso fazer sabe que pode contar comigo. E fique à vontade para questionar, indagar ou contra argumentar alguma request.

Forte abraço e agradeço novamente pelo empenho.

2023-02-20 12:10 UTC, thiagopuntar commented on src/components/Button/Button.stories.tsx
> +export const PrimaryWithIcon = Template.bind({});
Acho que você pode ter apenas uma story, porque é parametrizável.
O icon você pode fazer uma combobox com alguns icons pré prontos para ilustrar como funciona o button com o Icon e a position você pode programar isso no storybook pra inverter a ordem (pensando na utilização do button usando composition).
O storybook é altamente customizável dá pra criar sua story to jeito que quiser, e os controls também tem uma enorme customização. Acho que você vai curtir fazer isso, não é muito demorado. Procure por controls na documentação do storybook e veja como você pode fazer algo ultra parametrizável.

2023-02-20 12:10 UTC, thiagopuntar commented on src/pages/index.tsx
>  import type { NextPage } from "next";
Agora que a gente já está usando storybook, eu deixaria essa página apenas com um Hello World para a galera saber que pode mexer ainda, blz?

2023-02-21 19:24 UTC, closed without merging